import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.cluster import KMeans
from sklearn.metrics import accuracy_score, mean_squared_error, silhouette_score
import warnings

# Suppress annoying warnings
warnings.filterwarnings('ignore')

def preprocess_data(df, target_col=None, task_type="classification"):
    print("\n[1/4] Preprocessing data (handling missing values and encoding)...")
    
    # 1. Handle missing values
    for col in df.columns:
        if df[col].isnull().sum() > 0:
            if df[col].dtype == 'object':
                df[col] = df[col].fillna(df[col].mode()[0])
            else:
                df[col] = df[col].fillna(df[col].mean())
                
    # 2. Separate Features (X) and Target (y) if supervised
    if task_type in ["classification", "regression"]:
        if target_col not in df.columns:
            raise KeyError(f"Target column '{target_col}' not found in dataset.")
            
        X = df.drop(columns=[target_col])
        y = df[target_col]
        
        # One-Hot Encoding for categorical features in X
        X = pd.get_dummies(X, drop_first=True)
        
        # Handle labels for Classification vs Regression
        classes = None
        if task_type == "classification":
            label_encoder = LabelEncoder()
            y = label_encoder.fit_transform(y)
            classes = label_encoder.classes_
            
        return X, y, classes
        
    elif task_type == "unsupervised":
        # No target column for unsupervised learning
        X = pd.get_dummies(df, drop_first=True)
        return X, None, None

# ==========================================
# TinyML Export Functions
# ==========================================
def export_decision_tree(model, filename="tinyml_model.py", is_classifier=True, classes=None):
    tree = model.tree_
    features = tree.feature.tolist()
    thresholds = [round(x, 4) for x in tree.threshold.tolist()]
    left = tree.children_left.tolist()
    right = tree.children_right.tolist()
    
    with open(filename, "w", encoding="utf-8") as f:
        f.write("# Auto-Generated by TinyML AutoML\n")
        f.write(f"model_type = 'decision_tree_{'classifier' if is_classifier else 'regressor'}'\n")
        f.write(f"features = {features}\n")
        f.write(f"thresholds = {thresholds}\n")
        f.write(f"left = {left}\n")
        f.write(f"right = {right}\n")
        
        if is_classifier and classes is not None:
            node_classes = [str(classes[np.argmax(v)]) for v in tree.value]
            unique_classes = list(set(node_classes))
            class_indices = [unique_classes.index(c) for c in node_classes]
            f.write(f"unique_classes = {unique_classes}\n")
            f.write(f"class_indices = {class_indices}\n")
        else:
            # For regression, we just need the value at each node
            values = [round(float(v[0][0]), 4) for v in tree.value]
            f.write(f"values = {values}\n")

def export_linear_model(model, filename="tinyml_model.py", is_classifier=True, classes=None):
    weights = np.round(model.coef_[0] if is_classifier else model.coef_, 4).tolist()
    intercept = round(float(model.intercept_[0] if is_classifier else model.intercept_), 4)
    
    with open(filename, "w", encoding="utf-8") as f:
        f.write("# Auto-Generated by TinyML AutoML\n")
        f.write(f"model_type = '{'logistic_regression' if is_classifier else 'linear_regression'}'\n")
        f.write(f"weights = {weights}\n")
        f.write(f"intercept = {intercept}\n")
        if is_classifier and classes is not None:
            f.write(f"classes = {[str(c) for c in classes]}\n")

def export_kmeans(model, filename="tinyml_model.py"):
    centroids = np.round(model.cluster_centers_, 4).tolist()
    with open(filename, "w", encoding="utf-8") as f:
        f.write("# Auto-Generated by TinyML AutoML\n")
        f.write(f"model_type = 'kmeans_clustering'\n")
        f.write(f"centroids = {centroids}\n")
        f.write("n_clusters = len(centroids)\n")

# ==========================================
# Main Application CLI
# ==========================================
if __name__ == "__main__":
    print("=== Welcome to TinyML AutoML Platform ===")
    csv_path = input("Please enter the path to your CSV file (e.g., data.csv): ")
    
    print("\nSelect the Machine Learning Task Type:")
    print("1. Classification (Supervised - Predict a category/class)")
    print("2. Regression     (Supervised - Predict a continuous number)")
    print("3. Clustering     (Unsupervised - Grouping data without labels)")
    
    task_choice = input("Enter 1, 2, or 3: ")
    
    try:
        df = pd.read_csv(csv_path)
        
        if task_choice == '1':
            target_column = input("Enter the target column name (Label): ")
            X, y, classes = preprocess_data(df, target_column, "classification")
            
            print("\n[2/4] Splitting data into Train and Test sets...")
            X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
            
            print("\n[3/4] Training models: Decision Tree vs Logistic Regression...")
            dt = DecisionTreeClassifier(max_depth=6, random_state=42)
            dt.fit(X_train, y_train)
            dt_acc = accuracy_score(y_test, dt.predict(X_test))
            
            lr = LogisticRegression(max_iter=200, random_state=42)
            lr.fit(X_train, y_train)
            lr_acc = accuracy_score(y_test, lr.predict(X_test))
            
            print(f"  -> Decision Tree Accuracy: {dt_acc * 100:.2f}%")
            print(f"  -> Logistic Regression Accuracy: {lr_acc * 100:.2f}%")
            
            print("\n[4/4] Exporting the best classification model...")
            if dt_acc >= lr_acc:
                export_decision_tree(dt, is_classifier=True, classes=classes)
                print("🏆 Exported: Decision Tree Classifier")
            else:
                export_linear_model(lr, is_classifier=True, classes=classes)
                print("🏆 Exported: Logistic Regression")

        elif task_choice == '2':
            target_column = input("Enter the target column name (Label): ")
            X, y, _ = preprocess_data(df, target_column, "regression")
            
            print("\n[2/4] Splitting data into Train and Test sets...")
            X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
            
            print("\n[3/4] Training models: Decision Tree Regressor vs Linear Regression...")
            # Note: For regression, Mean Squared Error (MSE) is used. Lower is better!
            dtr = DecisionTreeRegressor(max_depth=6, random_state=42)
            dtr.fit(X_train, y_train)
            dtr_mse = mean_squared_error(y_test, dtr.predict(X_test))
            
            lin_reg = LinearRegression()
            lin_reg.fit(X_train, y_train)
            lin_reg_mse = mean_squared_error(y_test, lin_reg.predict(X_test))
            
            print(f"  -> Decision Tree MSE: {dtr_mse:.4f}")
            print(f"  -> Linear Regression MSE: {lin_reg_mse:.4f}")
            
            print("\n[4/4] Exporting the best regression model...")
            if dtr_mse <= lin_reg_mse:  # Lower MSE is better
                export_decision_tree(dtr, is_classifier=False)
                print("🏆 Exported: Decision Tree Regressor")
            else:
                export_linear_model(lin_reg, is_classifier=False)
                print("🏆 Exported: Linear Regression")

        elif task_choice == '3':
            X, _, _ = preprocess_data(df, task_type="unsupervised")
            
            print("\n[2/4] Unsupervised Learning does not require Train/Test splitting.")
            print("\n[3/4] Training model: K-Means Clustering...")
            
            # Using Silhouette Score to find the best 'K' (number of clusters) automatically
            best_k = 2
            best_score = -1
            best_model = None
            
            print("  -> Testing different cluster counts (K=2 to K=5)...")
            for k in range(2, min(6, len(X))):
                kmeans = KMeans(n_clusters=k, random_state=42)
                labels = kmeans.fit_predict(X)
                score = silhouette_score(X, labels)
                print(f"     K={k} | Silhouette Score: {score:.4f}")
                
                if score > best_score:
                    best_score = score
                    best_k = k
                    best_model = kmeans
                    
            print(f"\n  -> Best K found: {best_k} (Score: {best_score:.4f})")
            
            print("\n[4/4] Exporting K-Means Centroids...")
            export_kmeans(best_model)
            print("🏆 Exported: K-Means Clustering Model")

        else:
            print("❌ Invalid selection. Please restart and choose 1, 2, or 3.")
            exit()

        print("\n✅ Success! 'tinyml_model.py' has been generated for edge deployment.")

    except Exception as e:
        print(f"❌ Error during execution: {e}")